# FROM nginx:alpine

# COPY index.html /usr/share/nginx/html/index.html
# COPY style.css /usr/share/nginx/html/style.css
# COPY app.js /usr/share/nginx/html/app.js


FROM nginx:alpine

# 複製整個 client 資料夾的內容
COPY . /usr/share/nginx/html
