version: '3.9'

services:
  kms:
    build: ./kms
    container_name: kms-service
    ports:
      - "7000:7000"
    restart: unless-stopped

  web-server:
    build: ./server
    container_name: web-server
    ports:
      - "8000:8000"
    depends_on:
      - kms
    restart: unless-stopped
    volumes:
      - ./server/data:/app/data

  client-a:
    build:
      context: ./client
    container_name: client-a
    ports:
      - "8081:80"
    depends_on:
      - kms
      - web-server
    restart: unless-stopped

  client-b:
    build:
      context: ./client
    container_name: client-b
    ports:
      - "8082:80"
    depends_on:
      - kms
      - web-server
    restart: unless-stopped

  client-c:
    build:
      context: ./client
    container_name: client-c
    ports:
      - "8083:80"
    depends_on:
      - kms
      - web-server
    restart: unless-stopped
